packages:
  - packages/*

catalog:
  '@babel/cli': ^7.11.6
  '@babel/core': ^7.23.9
  '@babel/plugin-proposal-export-default-from': ^7.10.4
  '@babel/plugin-proposal-numeric-separator': ^7.10.4
  '@babel/plugin-syntax-dynamic-import': ^7.8.3
  '@babel/plugin-transform-class-properties': ^7.25.9
  '@babel/plugin-transform-nullish-coalescing-operator': ^7.25.9
  '@babel/plugin-transform-numeric-separator': ^7.25.9
  '@babel/plugin-transform-object-rest-spread': ^7.25.9
  '@babel/plugin-transform-optional-chaining': ^7.25.9
  '@babel/preset-env': ^7.23.9
  '@babel/preset-react': ^7.10.4
  '@babel/preset-typescript': ^7.10.4
  '@commitlint/cli': ^16.0.0
  '@commitlint/config-conventional': ^16.0.0
  '@dnd-kit/core': ^6.0.8
  '@dnd-kit/modifiers': ^6.0.1
  '@dnd-kit/sortable': ^7.0.2
  '@dnd-kit/utilities': ^3.2.2
  '@emotion/babel-plugin': ^11.13.5
  '@emotion/babel-preset-css-prop': ^11.11.0
  '@emotion/eslint-plugin': ^11.0.0
  '@emotion/jest': ^11.11.0
  '@emotion/react': ^11.11.1
  '@emotion/styled': ^11.11.0
  '@hapi/joi': ^17.0.2
  '@iarna/toml': 2.2.5
  '@octokit/rest': ^16.28.7
  '@reduxjs/toolkit': ^1.9.1
  '@simonsmith/cypress-image-snapshot': ^8.1.2
  '@soda/friendly-errors-webpack-plugin': ^1.8.1
  '@storybook/addon-actions': ^9.1.15
  '@storybook/addon-links': ^9.1.15
  '@storybook/react': ^9.1.15
  '@stylelint/postcss-css-in-js': ^0.37.2
  '@testing-library/dom': ^10.0.0
  '@testing-library/jest-dom': ^5.11.1
  '@testing-library/react': ^16.3.0
  '@types/common-tags': ^1.8.0
  '@types/cors': ^2.8.6
  '@types/express': ^4.17.15
  '@types/hapi__joi': 17.1.8
  '@types/history': ^4.7.8
  '@types/iarna__toml': ^2.0.5
  '@types/jest': ^27.0.0
  '@types/js-base64': ^3.0.0
  '@types/jwt-decode': ^2.2.1
  '@types/lodash': ^4.14.149
  '@types/morgan': ^1.7.37
  '@types/node': ^16.0.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@types/react-redux': ^7.1.33
  '@types/redux-mock-store': ^1.0.2
  '@types/url-join': ^4.0.0
  '@types/uuid': ^8.3.2
  '@types/vfile-message': ^2.0.0
  '@typescript-eslint/eslint-plugin': ^5.0.0
  '@typescript-eslint/parser': ^5.0.0
  '@vercel/stega': ^0.1.2
  '@vitejs/plugin-react': ^4.3.2
  ajv: ^8.17.1
  ajv-errors: ^3.0.0
  ajv-keywords: ^5.1.0
  all-contributors-cli: ^6.0.0
  apollo-cache-inmemory: ^1.6.2
  apollo-client: ^2.6.3
  apollo-link-context: ^1.0.18
  apollo-link-http: ^1.5.15
  array-move: 4.0.0
  async-mutex: ^0.3.0
  axios: ^1.6.0
  babel-core: ^7.0.0-bridge.0
  babel-eslint: ^11.0.0-beta.2
  babel-jest: ^27.5.1
  babel-loader: ^8.0.5
  babel-plugin-emotion: ^10.0.9
  babel-plugin-inline-import: ^3.0.0
  babel-plugin-inline-json-import: ^0.3.2
  babel-plugin-inline-react-svg: ^2.0.0
  babel-plugin-transform-builtin-extend: ^1.1.2
  babel-plugin-transform-define: 2.0.1
  babel-plugin-transform-export-extensions: ^6.22.0
  babel-plugin-transform-inline-environment-variables: ^0.4.3
  browserify: ^17.0.0
  buffer: ^6.0.3
  cache-me-outside: ^0.0.10
  clean-stack: ^5.2.0
  codemirror: ^5.46.0
  common-tags: 1.8.2
  commonmark: ^0.30.0
  commonmark-spec: ^0.30.0
  copy-text-to-clipboard: ^3.0.0
  copy-webpack-plugin: ^10.2.4
  cors: ^2.8.5
  create-react-class: ^15.7.0
  cross-env: ^7.0.0
  css-loader: ^7.1.2
  cypress: ^12.17.4
  cypress-jest-adapter: ^0.1.1
  cypress-plugin-tab: ^1.0.0
  dayjs: ^1.11.10
  deepmerge: ^4.2.2
  detab: ^2.0.4
  diacritics: ^1.3.0
  dompurify: ^3.2.6
  dotenv: ^10.0.0
  emotion: ^11.0.0
  eslint: ^8.12.0
  eslint-config-prettier: ^8.0.0
  eslint-plugin-babel: ^5.3.0
  eslint-plugin-cypress: ^2.6.0
  eslint-plugin-import: ^2.18.2
  eslint-plugin-prettier: ^4.0.0
  eslint-plugin-react: ^7.17.0
  eslint-plugin-storybook: ^9.1.15
  eslint-plugin-unicorn: ^41.0.1
  execa: ^5.0.0
  express: ^4.18.2
  file-loader: ^6.2.0
  fs-extra: ^10.0.0
  fuzzy: ^0.1.1
  gitlab: ^14.1.1
  globby: ^12.0.0
  gotrue-js: ^0.9.24
  graphql: ^15.0.0
  graphql-tag: ^2.10.1
  gray-matter: ^4.0.2
  history: ^4.7.2
  http-server: ^14.0.0
  husky: ^7.0.0
  immer: ^9.0.0
  immutable: ^3.7.6
  imports-loader: ^4.0.1
  ini: ^2.0.0
  is-hotkey: ^0.2.0
  is-url: ^1.2.4
  jest: ^27.0.0
  jest-cli: ^27.0.0
  jest-environment-jsdom: ^27.0.0
  jest-mock: ^27.0.0
  js-base64: ^3.0.0
  js-sha256: ^0.9.0
  js-yaml: ^4.0.0
  jsdom: ^25.0.1
  jwt-decode: ^3.0.0
  lerna: ^8.0.2
  localforage: ^1.7.3
  lodash: ^4.17.11
  lodash-es: ^4.17.21
  mdast-util-definitions: ^1.2.3
  mdast-util-to-string: ^1.0.5
  minimatch: ^7.0.0
  mockserver-client: ^5.8.0
  mockserver-node: ^5.8.0
  morgan: ^1.9.1
  ncp: ^2.0.0
  nock: ^13.0.0
  node-fetch: ^2.3.0
  node-polyfill-webpack-plugin: ^4.1.0
  node-polyglot: ^2.3.0
  nodemon: ^2.0.2
  npm: ^9.9.2
  npm-run-all: ^4.1.5
  nx: ^21.1.0
  ol: ^6.9.0
  path-browserify: ^1.0.1
  postcss: ^8.4.7
  postcss-scss: ^4.0.3
  prettier: ^2.3.0
  process: ^0.11.10
  prop-types: ^15.7.2
  react: ^19.1.0
  react-aria-menubutton: ^7.0.0
  react-codemirror2: ^7.0.0
  react-color: ^2.18.1
  react-dnd: ^14.0.0
  react-dnd-html5-backend: ^14.0.0
  react-dom: ^19.1.0
  react-frame-component: ^5.2.1
  react-immutable-proptypes: ^2.1.0
  react-is: 16.13.1
  react-markdown: ^6.0.2
  react-modal: ^3.8.1
  react-polyglot: ^0.7.0
  react-redux: ^7.2.0
  react-router: ^5.3.4
  react-router-dom: ^5.2.0
  react-scroll-sync: ^0.11.2
  react-select: ^5.10.0
  react-split-pane: ^0.1.85
  react-textarea-autosize: ^8.0.0
  react-toastify: ^9.1.1
  react-topbar-progress-indicator: ^4.0.0
  react-transition-group: ^4.4.5
  react-virtualized-auto-sizer: ^1.0.2
  react-waypoint: ^10.0.0
  react-window: ^1.8.5
  redux: ^4.0.5
  redux-devtools-extension: ^2.13.8
  redux-mock-store: ^1.5.3
  redux-notifications: ^4.0.1
  redux-thunk: ^2.3.0
  rehype: ^7.0.0
  rehype-parse: ^6.0.0
  rehype-remark: ^8.0.0
  rehype-stringify: ^7.0.0
  remark-gfm: 1.0.0
  remark-parse: ^6.0.3
  remark-rehype: ^4.0.0
  remark-slate: ^1.8.6
  remark-slate-transformer: ^0.7.4
  remark-stringify: ^6.0.4
  rimraf: ^3.0.0
  sanitize-filename: ^1.6.1
  semaphore: ^1.1.0
  simple-git: ^3.0.0
  slate: ^0.118.1
  slate-base64-serializer: ^0.2.107
  slate-dom: ^0.118.1
  slate-history: ^0.113.1
  slate-hyperscript: ^0.100.0
  slate-plain-serializer: ^0.7.3
  slate-react: ^0.117.4
  slate-soft-break: ^0.9.0
  start-server-and-test: ^1.7.11
  stream-browserify: ^3.0.0
  style-loader: ^3.3.3
  stylelint: ^14.5.3
  stylelint-config-standard-scss: ^3.0.0
  stylelint-config-styled-components: ^0.1.1
  stylelint-processor-styled-components: ^1.10.0
  svg-inline-loader: ^0.8.0
  svgo-loader: ^3.0.3
  tinycolor2: ^1.4.1
  to-string-loader: ^1.1.5
  tomlify-j0.4: ^3.0.0-alpha.0
  ts-jest: ^27.0.0
  ts-loader: ^9.4.2
  ts-node: ^10.9.1
  tsconfig-paths-webpack-plugin: ^3.2.0
  typescript: ^4.9.4
  unified: ^9.2.0
  unist-builder: ^1.0.3
  unist-util-visit: ^1.4.0
  unist-util-visit-parents: ^2.0.1
  uploadcare-widget: ^3.7.0
  uploadcare-widget-tab-effects: ^1.4.0
  url: ^0.11.0
  url-join: ^4.0.1
  uuid: ^8.3.2
  vfile-location: ^2.0.6
  vite: ^5.4.8
  vitest: ^2.1.2
  webpack: ^5.75.0
  webpack-cli: ^5.0.1
  webpack-dev-server: ^4.11.1
  webpack-node-externals: ^3.0.0
  what-input: ^5.1.4
  what-the-diff: ^0.6.0
  winston: ^3.3.3
  yaml: ^1.8.3

onlyBuiltDependencies:
  - '@swc/core'
  - bufferutil
  - core-js
  - cypress
  - es5-ext
  - esbuild
  - nx
  - utf-8-validate
